api:
  port: "8000"

user:
  signing_key: "jbds82sk0da[s"
  access_token_lifetime: 60
  refresh_token_lifetime: 43200

postgres_db:
  username: "postgres"
  host: "localhost"
  port: "5420"
  dbname: "fantasy_db"
  sslmode: "disable"
  password: "Qbpsd24mdds"

redis_db:
  host: "localhost"
  port: "6379"
  password: "Udnl2-X8dp%sd"