api:
  port: "8000"

user:
  signing_key: "jbds82sk0da[s"
  access_token_lifetime: 60
  refresh_token_lifetime: 43200

db:
  username: "postgres"
  host: "localhost"
  port: "5420"
  dbname: "fantasy_db"
  sslmode: "disable"
  password: "Qbpsd24mdds"