// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/email/send-code": {
            "post": {
                "description": "Отправка письма с кодом для подтверждения email пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Отправка кода подтверждения",
                "parameters": [
                    {
                        "description": "Входные параметры",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.EmailInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Выход пользователя из системы",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход из системы",
                "parameters": [
                    {
                        "description": "Входные параметры",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.RefreshInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/auth/refresh-tokens": {
            "post": {
                "description": "Обновление access и refresh токенов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Обновление токенов",
                "parameters": [
                    {
                        "description": "Входные параметры",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.RefreshInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.Tokens"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/auth/sign-in": {
            "post": {
                "description": "Авторизация пользователя в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Авторизация",
                "parameters": [
                    {
                        "description": "Входные параметры",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.SignInInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.Tokens"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/auth/sign-up": {
            "post": {
                "description": "Регистрация нового пользователя в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация",
                "parameters": [
                    {
                        "description": "Входные параметры",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.SignUpInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/players": {
            "get": {
                "description": "Получение списка игроков",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Получение списка игроков",
                "parameters": [
                    {
                        "type": "string",
                        "description": "profileID",
                        "name": "profileID",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "description": "players",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "description": "teams",
                        "name": "teams",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "G",
                            "D",
                            "F"
                        ],
                        "type": "string",
                        "description": "position",
                        "name": "position",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "NHL",
                            "KHL"
                        ],
                        "type": "string",
                        "description": "league",
                        "name": "league",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.PlayerResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/players/cards": {
            "get": {
                "description": "Получение списка карточек игроков",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Получение списка карточек игроков",
                "parameters": [
                    {
                        "type": "string",
                        "description": "profileID",
                        "name": "profileID",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "Silver",
                            "Gold"
                        ],
                        "type": "string",
                        "description": "rarity",
                        "name": "rarity",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "NHL",
                            "KHL"
                        ],
                        "type": "string",
                        "description": "league",
                        "name": "league",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "unpacked",
                        "name": "unpacked",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.PlayerCardResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/players/cards/unpack": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Распаковка карточки игрока",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Распаковка карточки игрока",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "id карточки",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/players/khl/create": {
            "post": {
                "description": "Добавление игроков КХЛ в базу данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Добавление игроков КХЛ",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/players/nhl/create": {
            "post": {
                "description": "Добавление игроков НХЛ в базу данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Добавление игроков НХЛ",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/players/statistic_player/{player_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращается все поля статистики за всё время",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Получение полной статистики по id игрока",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id игрока",
                        "name": "player_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.PlayersStatisticDB"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/store/products": {
            "get": {
                "description": "Получение списка товаров из fantasy магазина",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "store"
                ],
                "summary": "Получение товаров из fantasy магазина",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_store.Product"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/store/products/buy": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Покупка товара в магазине по id товара",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "store"
                ],
                "summary": "Покупка товара в магазине",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "id товара",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/tournament/create_team_khl": {
            "get": {
                "description": "Добавлят информацию о команде KHL",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournament"
                ],
                "summary": "Создание команд KHL",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/tournament/create_team_nhl": {
            "get": {
                "description": "Добавлят информацию о команде NHL",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournament"
                ],
                "summary": "Создание команд NHL",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/tournament/get_matches/{league}": {
            "get": {
                "description": "Дата берётся автоматически",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournament"
                ],
                "summary": "Получение матчей на следующий день",
                "parameters": [
                    {
                        "enum": [
                            "NHL",
                            "KHL"
                        ],
                        "type": "string",
                        "description": "league",
                        "name": "league",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.Matches"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/tournament/get_tournaments/{league}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Дата берётся автоматически",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournament"
                ],
                "summary": "Получение турниров на ближайшие 2 дня",
                "parameters": [
                    {
                        "enum": [
                            "NHL",
                            "KHL",
                            "Both"
                        ],
                        "type": "string",
                        "description": "league",
                        "name": "league",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.Tournament"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/tournament/matches_by_tournament_id/{tournament_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращается вся необходимая информация о матчах",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournament"
                ],
                "summary": "Получение матчей по id турнира",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id турнира",
                        "name": "tournament_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.GetMatchesByTourId"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/tournament/results": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получение результатов турнира",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournament"
                ],
                "summary": "Получение результатов турнира",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tournamentID",
                        "name": "tournamentID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.TournamentResults"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/tournament/roster": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получение составов на турнир",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournament"
                ],
                "summary": "Получение составов на турнир",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tournamentID",
                        "name": "tournamentID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.TournamentRosterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/tournament/team": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получение команды пользователя в турнире",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournament"
                ],
                "summary": "Получение команды пользователя в турнире",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tournamentID",
                        "name": "tournamentID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.UserTeamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/tournament/team/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создание команды пользователя в турнире",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournament"
                ],
                "summary": "Создание команды пользователя в турнире",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tournamentID",
                        "name": "tournamentID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Входные параметры",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.UserTeamInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/tournament/team/edit": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Редактирование команды пользователя в турнире",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournament"
                ],
                "summary": "Редактирование команды пользователя в турнире",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tournamentID",
                        "name": "tournamentID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Входные параметры",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.UserTeamInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/tournaments": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получение турниров",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tournament"
                ],
                "summary": "Получение турниров",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "tournamentID",
                        "name": "tournamentID",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "NHL",
                            "KHL"
                        ],
                        "type": "string",
                        "description": "league",
                        "name": "league",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "not_yet_started",
                            "started",
                            "finished",
                            "active"
                        ],
                        "type": "string",
                        "description": "status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "all",
                            "personal"
                        ],
                        "type": "string",
                        "description": "type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.Tournament"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/user/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаление профиля пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Удаление профиля",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/user/exists": {
            "get": {
                "description": "Существует ли уже пользователь с таким email или nickname. Код 200: пользователь с такими данными уже существует, код 404: пользователь с такими данными не найден.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Существует ли пользователь с указанными параметрами",
                "parameters": [
                    {
                        "type": "string",
                        "example": "test@test.test",
                        "description": "Email пользователя",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "Qwerty1",
                        "description": "Nickname пользователя",
                        "name": "nickname",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получение пользовательской информации по access токену",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получение информации о пользователе",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.UserInfoModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/user/password/change": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Смена пароля",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Смена пароля",
                "parameters": [
                    {
                        "description": "Входные параметры",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.ChangePasswordInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/user/password/forgot": {
            "post": {
                "description": "Отправка письма с информацией о сбросе пароля",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Забыли пароль",
                "parameters": [
                    {
                        "description": "Входные параметры",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.EmailInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/user/password/reset": {
            "patch": {
                "description": "Восстановление пароля",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Восстановление пароля",
                "parameters": [
                    {
                        "description": "Входные параметры",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.ResetPasswordInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        },
        "/user/transactions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получение истории транзакций пользователя по access токену",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получение истории транзакций пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.CoinTransactionsModel"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.FullPlayerStatInfo": {
            "type": "object",
            "properties": {
                "assists": {
                    "type": "integer"
                },
                "fantasyPoint": {
                    "type": "number"
                },
                "gameDate": {
                    "type": "string"
                },
                "goals": {
                    "type": "integer"
                },
                "hits": {
                    "type": "integer"
                },
                "missedGoals": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "opponent": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "pims": {
                    "type": "integer"
                },
                "playerID": {
                    "type": "integer"
                },
                "position": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.Position"
                },
                "positionName": {
                    "type": "string"
                },
                "rarity": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_store.CardRarity"
                },
                "rarityName": {
                    "type": "string"
                },
                "saves": {
                    "type": "integer"
                },
                "shots": {
                    "type": "integer"
                },
                "shutout": {
                    "type": "boolean"
                },
                "teamLogo": {
                    "type": "string"
                },
                "teamName": {
                    "type": "string"
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.PlayerCardResponse": {
            "type": "object",
            "properties": {
                "bonusMetric": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_store.BonusMetric"
                },
                "bonusMetricName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "league": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.League"
                },
                "leagueName": {
                    "type": "string"
                },
                "multiply": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "playerID": {
                    "type": "integer"
                },
                "position": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.Position"
                },
                "positionName": {
                    "type": "string"
                },
                "profileID": {
                    "type": "string"
                },
                "rarity": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_store.CardRarity"
                },
                "rarityName": {
                    "type": "string"
                },
                "sweaterNumber": {
                    "type": "integer"
                },
                "teamID": {
                    "type": "integer"
                },
                "teamLogo": {
                    "type": "string"
                },
                "teamName": {
                    "type": "string"
                },
                "unpacked": {
                    "type": "boolean"
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.PlayerResponse": {
            "type": "object",
            "properties": {
                "avgFantasyPoints": {
                    "type": "number"
                },
                "cardRarity": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_store.CardRarity"
                },
                "id": {
                    "type": "integer"
                },
                "league": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.League"
                },
                "leagueName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "playerCost": {
                    "type": "number"
                },
                "position": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.Position"
                },
                "positionName": {
                    "type": "string"
                },
                "rarityName": {
                    "type": "string",
                    "default": "Default"
                },
                "sweaterNumber": {
                    "type": "integer"
                },
                "teamID": {
                    "type": "integer"
                },
                "teamLogo": {
                    "type": "string"
                },
                "teamName": {
                    "type": "string"
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.PlayersStatisticDB": {
            "type": "object",
            "properties": {
                "assists": {
                    "type": "integer"
                },
                "fantasyPoint": {
                    "type": "number"
                },
                "gameDate": {
                    "type": "string"
                },
                "goals": {
                    "type": "integer"
                },
                "hits": {
                    "type": "integer"
                },
                "league": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.League"
                },
                "matchIdLocal": {
                    "type": "integer"
                },
                "missedGoals": {
                    "type": "integer"
                },
                "opponent": {
                    "type": "string"
                },
                "pims": {
                    "type": "integer"
                },
                "playerIdNhl": {
                    "type": "integer"
                },
                "saves": {
                    "type": "integer"
                },
                "shots": {
                    "type": "integer"
                },
                "shutout": {
                    "type": "boolean"
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.Position": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "ErrPlayerPosition",
                "Goalie",
                "Defensemen",
                "Forward"
            ]
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.PositionData": {
            "type": "object",
            "properties": {
                "positionAbbrev": {
                    "type": "string"
                },
                "positionName": {
                    "type": "string"
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.TeamData": {
            "type": "object",
            "properties": {
                "teamAbbrev": {
                    "type": "string"
                },
                "teamID": {
                    "type": "integer"
                },
                "teamName": {
                    "type": "string"
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.TournamentResults": {
            "type": "object",
            "properties": {
                "coins": {
                    "type": "integer"
                },
                "fantasyPoints": {
                    "type": "number"
                },
                "nickname": {
                    "type": "string"
                },
                "place": {
                    "type": "integer"
                },
                "profileID": {
                    "type": "string"
                },
                "userPhoto": {
                    "type": "string"
                },
                "userTeam": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.FullPlayerStatInfo"
                    }
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.TournamentRosterResponse": {
            "type": "object",
            "properties": {
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.PlayerResponse"
                    }
                },
                "positions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.PositionData"
                    }
                },
                "teams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.TeamData"
                    }
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.UserTeamResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_players.PlayerResponse"
                    }
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_store.BonusMetric": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "ErrPlayerMetric",
                "GoalieMetric",
                "DefensemenMetric",
                "ForwardMetric"
            ]
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_store.CardRarity": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "ErrCardRarity",
                "Silver",
                "Gold"
            ]
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_store.Product": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "league": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.League"
                },
                "leagueName": {
                    "type": "string"
                },
                "photoLink": {
                    "type": "string"
                },
                "playerCardsCount": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "productName": {
                    "type": "string"
                },
                "rarity": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_store.CardRarity"
                },
                "rarityName": {
                    "type": "string"
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.GetMatchesByTourId": {
            "type": "object",
            "properties": {
                "awayScore": {
                    "type": "integer"
                },
                "awayTeamAbbrev": {
                    "type": "string"
                },
                "awayTeamId": {
                    "type": "integer"
                },
                "awayTeamLogo": {
                    "type": "string"
                },
                "endAt": {
                    "type": "string"
                },
                "eventId": {
                    "type": "integer"
                },
                "homeScore": {
                    "type": "integer"
                },
                "homeTeamAbbrev": {
                    "type": "string"
                },
                "homeTeamId": {
                    "type": "integer"
                },
                "homeTeamLogo": {
                    "type": "string"
                },
                "league": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.League"
                },
                "matchId": {
                    "type": "integer"
                },
                "startAt": {
                    "type": "string"
                },
                "statusEvent": {
                    "type": "string"
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.League": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "ErrLeague",
                "NHL",
                "KHL"
            ]
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.Matches": {
            "type": "object",
            "properties": {
                "awayScore": {
                    "type": "integer"
                },
                "awayTeamId": {
                    "type": "integer"
                },
                "endAt": {
                    "type": "integer"
                },
                "eventId": {
                    "type": "integer"
                },
                "homeScore": {
                    "type": "integer"
                },
                "homeTeamId": {
                    "type": "integer"
                },
                "league": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.League"
                },
                "matchId": {
                    "type": "integer"
                },
                "startAt": {
                    "type": "integer"
                },
                "statusEvent": {
                    "type": "string"
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.Tournament": {
            "type": "object",
            "properties": {
                "deposit": {
                    "type": "integer"
                },
                "league": {
                    "$ref": "#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.League"
                },
                "matchesIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "playersAmount": {
                    "type": "integer"
                },
                "prizeFond": {
                    "type": "integer"
                },
                "statusParticipation": {
                    "type": "boolean"
                },
                "statusTournament": {
                    "type": "string"
                },
                "timeEnd": {
                    "type": "integer"
                },
                "timeEndTS": {
                    "type": "string"
                },
                "timeStart": {
                    "type": "integer"
                },
                "timeStartTS": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "tournamentId": {
                    "type": "integer"
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_tournaments.UserTeamInput": {
            "type": "object",
            "properties": {
                "team": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.ChangePasswordInput": {
            "type": "object",
            "required": [
                "newPassword",
                "oldPassword"
            ],
            "properties": {
                "newPassword": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                },
                "oldPassword": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.CoinTransactionsModel": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "profileID": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "transactionDate": {
                    "type": "string"
                },
                "transactionDetails": {
                    "type": "string"
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.EmailInput": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 64
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.RefreshInput": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 64
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.ResetPasswordInput": {
            "type": "object",
            "required": [
                "hash",
                "newPassword"
            ],
            "properties": {
                "hash": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 32
                },
                "newPassword": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.SignInInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 64
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.SignUpInput": {
            "type": "object",
            "required": [
                "code",
                "email",
                "nickname",
                "password"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                },
                "email": {
                    "type": "string",
                    "maxLength": 64
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 4
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.Tokens": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "expiresIn": {
                    "type": "integer"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.UserInfoModel": {
            "type": "object",
            "properties": {
                "coins": {
                    "type": "integer"
                },
                "dateRegistration": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "photoLink": {
                    "type": "string"
                },
                "profileID": {
                    "type": "string"
                }
            }
        },
        "pkg_api.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "pkg_api.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "fantasy api doc",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
