definitions:
  github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.ChangePasswordInput:
    properties:
      newPassword:
        maxLength: 64
        minLength: 8
        type: string
      oldPassword:
        maxLength: 64
        minLength: 8
        type: string
    required:
    - newPassword
    - oldPassword
    type: object
  github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.EmailInput:
    properties:
      email:
        maxLength: 64
        type: string
    required:
    - email
    type: object
  github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.NicknameInput:
    properties:
      nickname:
        maxLength: 64
        minLength: 4
        type: string
    required:
    - nickname
    type: object
  github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.RefreshInput:
    properties:
      refreshToken:
        type: string
    required:
    - refreshToken
    type: object
  github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.ResetPasswordInput:
    properties:
      hash:
        type: string
      newPassword:
        maxLength: 64
        minLength: 8
        type: string
    required:
    - hash
    - newPassword
    type: object
  github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.SignInInput:
    properties:
      email:
        maxLength: 64
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.SignUpInput:
    properties:
      code:
        type: integer
      email:
        maxLength: 64
        type: string
      nickname:
        maxLength: 64
        minLength: 4
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
    required:
    - code
    - email
    - nickname
    - password
    type: object
  github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.Tokens:
    properties:
      accessToken:
        type: string
      expiresIn:
        type: integer
      refreshToken:
        type: string
    type: object
  github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.UserInfoModel:
    properties:
      coins:
        type: integer
      dateRegistration:
        type: string
      email:
        type: string
      nickname:
        type: string
      photoLink:
        type: string
      profileID:
        type: string
    type: object
  pkg_api.Error:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  pkg_api.StatusResponse:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
  title: fantasy api doc
paths:
  /auth/email/send-code:
    post:
      consumes:
      - application/json
      description: Отправка письма с кодом для подтверждения email пользователя
      parameters:
      - description: Входные параметры
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.EmailInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_api.StatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api.Error'
      summary: Отправка кода подтверждения
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Выход пользователя из системы
      parameters:
      - description: Входные параметры
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.RefreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_api.StatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api.Error'
      summary: Выход из системы
      tags:
      - auth
  /auth/refresh-tokens:
    post:
      consumes:
      - application/json
      description: Обновление access и refresh токенов
      parameters:
      - description: Входные параметры
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.RefreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.Tokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api.Error'
      summary: Обновление токенов
      tags:
      - auth
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя в системе
      parameters:
      - description: Входные параметры
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.Tokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api.Error'
      summary: Авторизация
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Регистрация нового пользователя в системе
      parameters:
      - description: Входные параметры
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.SignUpInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_api.StatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api.Error'
      summary: Регистрация
      tags:
      - auth
  /user/check-email:
    post:
      consumes:
      - application/json
      description: Существует ли уже пользователь с таким email
      parameters:
      - description: Входные параметры
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.EmailInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_api.StatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api.Error'
      summary: Использован ли данный email в сервисе
      tags:
      - user
  /user/check-nickname:
    post:
      consumes:
      - application/json
      description: Существует ли уже пользователь с таким nickname
      parameters:
      - description: Входные параметры
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.NicknameInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_api.StatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api.Error'
      summary: Использован ли данный nickname в сервисе
      tags:
      - user
  /user/info:
    get:
      consumes:
      - application/json
      description: Получение пользовательской информации по access токену
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.UserInfoModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/pkg_api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api.Error'
      security:
      - ApiKeyAuth: []
      summary: Получение информации о пользователе
      tags:
      - user
  /user/password/change:
    patch:
      consumes:
      - application/json
      description: Смена пароля
      parameters:
      - description: Входные параметры
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.ChangePasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_api.StatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/pkg_api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api.Error'
      security:
      - ApiKeyAuth: []
      summary: Смена пароля
      tags:
      - user
  /user/password/forgot:
    post:
      consumes:
      - application/json
      description: Отправка письма с информацией о сбросе пароля
      parameters:
      - description: Входные параметры
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.EmailInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_api.StatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api.Error'
      summary: Забыли пароль
      tags:
      - user
  /user/password/reset:
    patch:
      consumes:
      - application/json
      description: Восстановление пароля
      parameters:
      - description: Входные параметры
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_Frozen-Fantasy_fantasy-backend_git_pkg_models_user.ResetPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_api.StatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg_api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api.Error'
      summary: Восстановление пароля
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
